//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.24 at 10:43:45 AM CEST 
//


package contacts.mysan.roman.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="personInfoDTO" type="{roman.mysan.contacts/soap}personInfoDTO"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "personInfoDTO"
})
@XmlRootElement(name = "getSearchResponse")
public class GetSearchResponse {

    @XmlElement(required = true)
    protected List<PersonInfoDTO> personInfoDTO;

    /**
     * Gets the value of the personInfoDTO property.
     * 
     * @return
     *     possible object is
     *     {@link PersonInfoDTO }
     *     
     */
    public List<PersonInfoDTO> getPersonInfoDTO() {
        return personInfoDTO;
    }

    /**
     * Sets the value of the personInfoDTO property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonInfoDTO }
     *     
     */
    public void setPersonInfoDTO(List<PersonInfoDTO> value) {
        this.personInfoDTO = value;
    }

}
